---
title: "Using `wf4ni` for Resting State fMRI processing"
author: "Domingo López-Rodríguez"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using `wf4ni` for Resting State fMRI processing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = nzchar(Sys.getenv("MY_EVAL_VARIABLE"))
)
```

```{r messages = FALSE, warning=FALSE}
suppressPackageStartupMessages(library(wf4ni))
suppressPackageStartupMessages(library(tidyverse))
```

# Objective

# Requirements

## Packages

```{r}
library(neurobase)
library(fslr)
library(readr)
library(oro.nifti)
library(ANTsR)
library(signal)
```


## Other Resources

# fMRI Processing

```{r fmri_flow}
fmri_flow <- NIflow$new(name = "fmri",
                        inputs = c("T1", "BOLD", "TR", "atlas"))
```


## Slice Time Correction

```{r slice_time}
# slice time correction
correct_slice_time <- function(bold) {

  my_bold <- checkimg(bold)

  bold_corrected <- fslslicetimer(file = my_bold)

  return(bold_corrected)

}
```

```{r slice_time_flow}
fmri_flow %>%
  add(what = correct_slice_time,
      inputs = "BOLD",
      output = "bold_slice_time")
```

## Motion Correction

```{r motion_correction}
# run motion correction
correct_motion <- function(bold) {

  my_bold <- checkimg(bold)

  outfile <- tempfile()

  res <- fslr::mcflirt(file = my_bold,
                       outfile = outfile,
                       opts = "-plots")

  pars <- read_delim(file = paste0(outfile, ".par"),
                     delim = " ",
                     col_names = FALSE,
                     trim_ws = TRUE,
                     col_types = cols())

  pars_file <- gsub(pattern = "  ",
                    replacement = " ",
                    x = read_file(paste0(outfile, ".par")))

  pars <- read_delim(pars_file,
                     delim = " ",
                     col_names = FALSE)[, 1:6] %>%
    as.matrix()

  return(list(image = res, pars = pars))

}

# regressing out motion correction parameters
regress_out_motion <- function(L) {

  bold <- L$image
  params <- L$pars

  dims <- dim(bold)
  my_fit <- array(0, dim = dims)

  dim(bold) <- c(dims[1] * dims[2] * dims[3], dims[4])
  tmp_mean <- apply(bold, 1, mean)
  dim(tmp_mean) <- dims[1:3]
  dim(bold) <- dims

  for (z in seq(dims[3])) {

    tmp_data <- bold[, , z, ]

    dim(tmp_data) <- c(dims[1] * dims[2], dims[4])

    tmp_data <- t(tmp_data)

    fit <- lm(tmp_data ~ params)

    my_fit[, , z, ] <- t(fit$residuals)

  }

  for (t in seq(dims[4])) {

    my_fit[, , , t] <- my_fit[, , , t] + tmp_mean

  }

  my_fit <- my_fit - min(my_fit)
  my_fit <- my_fit / max(my_fit) * 30000

  return(as.nifti(my_fit, value = bold))

}
```

```{r motion_correction_flow}
fmri_flow %>%
  add(what = correct_motion,
      inputs = "bold_slice_time",
      output = "motion_estimation") %>%
  add(what = regress_out_motion,
      inputs = "motion_estimation",
      output = "bold_motion_regressed")
```

## Skull Strip Functional Image

```{r skull_strip}
#first create mean_func
compute_mean_func <- function(image) {

  dims <- dim(image)

  res <- array(0, dim = dims[1:3])

  for (t in seq(dims[4])) {

    res <- res + image[, , , t]

  }

  res <- res / dims[4]

  return(as.nifti(res, value = image))

}

#now skull strip the mean
skull_strip <- function(image) {


  my_file <- checkimg(image)
  res <- fslbet(infile = my_file, opts = "-m")

  return(res)

}

#now mask full run by results
mask_run <- function(image, mask) {

  masked <- fslmask(file = checkimg(image),
                    mask = checkimg(mask > 0))

  return(masked)

}
```

```{r skull_strip_flow}
fmri_flow %>%
  add(what = compute_mean_func,
      inputs = "bold_motion_regressed",
      output = "mean_func") %>%
  add(what = skull_strip,
      inputs = "mean_func",
      output = "mean_func_brain") %>%
  add(what = mask_run,
      inputs = c("bold_motion_regressed", "mean_func_brain"),
      output = "bold_masked") %>%
  add(what = skull_strip,
      inputs = "T1",
      output = "T1_brain")
```


## Normalize data

```{r normalization}
# normalize the data
normalize_data <- function(t1_ss, bold_ss) {

  fsldir <- getOption("fsl.path")
  flirtref <- file.path(fsldir, 'data', 'standard',
                        'MNI152_T1_2mm_brain.nii.gz')

  my_t1 <- checkimg(t1_ss)
  my_bold <- checkimg(bold_ss)

  res <- fslsplit(infile = my_bold, direction = "t")
  my_bold1 <- checkimg(res[[1]])

  func2t1_mat <- tempfile(fileext = ".mat")
  t12standard_mat <- tempfile(fileext = ".mat")
  t12func_mat <- tempfile(fileext = ".mat")
  standard2t1_mat <- tempfile(fileext = ".mat")
  func2standard_mat  <- tempfile(fileext = ".mat")

  #first flirt the func to the t1
  tmp <- flirt(infile = my_bold1,
                     reffile = my_t1,
                     omat = func2t1_mat,
                     opts = "-cost corratio -dof 6 -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -interp trilinear")

  #invert the mat

  cmd_base <- get.fsl()

  cmd <- paste0(cmd_base,
                "convert_xfm -inverse ", func2t1_mat,
                " -omat ", t12func_mat)

  system(cmd, intern = TRUE)

  #flirt the t1 to standard
  t12std_img <- flirt(infile = my_t1,
                     reffile = flirtref,
                     omat = t12standard_mat,
                     opts = " -cost corratio -dof 12 -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -interp trilinear")

  #invert the mat
  cmd <- paste0(cmd_base,
                "convert_xfm -inverse ", t12standard_mat,
                " -omat ", standard2t1_mat)

  system(cmd, intern = TRUE)

  #compute the func2standard mat

  cmd <- paste0(cmd_base,
                "convert_xfm -omat ", func2standard_mat,
                " -concat ", t12standard_mat, " ", func2t1_mat)

  system(cmd, intern = TRUE)

  #apply the transform
  func2std_img <- flirt_apply(infile = my_bold,
                                    reffile = flirtref,
                                    initmat = func2standard_mat,
                                    opts = " -interp trilinear")

  return(list(t12std_img = t12std_img,
              func2std_img = func2std_img))

}

get_t12std <- function(L) L$t12std_img
get_func2std <- function(L) L$func2std_img
```

```{r normalization_flow}
fmri_flow %>%
  add(what = normalize_data,
      inputs = c("T1_brain", "bold_masked"),
      output = "all_normalized") %>%
  add(what = get_t12std,
      inputs = "all_normalized",
      output = "t12std") %>%
  add(what = get_func2std,
      inputs = "all_normalized",
      output = "func2std")
```

## Regress out WM and CSF Signals

```{r regress_wm_csf}
# regress out WM/CSF
regress_out_wm_csf <- function(func2std_img) {

  base_dir <- "./resources/rsfMRI/"

  refwm <- file.path(base_dir, 'data',
                     'MNI152_T1_2mm_brain_pve_2.nii.gz')
  refcsf <- file.path(base_dir, 'data',
                      'MNI152_T1_2mm_brain_pve_0.nii.gz')

  wmout <- tempfile(fileext = ".txt")
  csfout <- tempfile(fileext = ".txt")

  cmd_base <- get.fsl()

  if (is.nifti(func2std_img)) {

    img <- tempfile(fileext = ".nii.gz")
    writenii(func2std_img, filename = img, dtype = FALSE)

  }
  # img <- checkimg(func2std_img)

  #mean time series for wm
  cmd <- paste0(cmd_base,
                "fslmeants -i ", img,
                " -m ", refwm, " -o ", wmout)

  system(cmd, intern = TRUE)

  #mean time series for csf
  cmd <- paste0(cmd_base,
                "fslmeants -i ", img,
                " -m ", refcsf, " -o ", csfout)

  system(cmd, intern = TRUE)

  wm_ts <- read.csv(wmout, header = FALSE) %>% unlist()
  csf_ts <- read.csv(csfout, header = FALSE) %>% unlist()

  dims <- dim(func2std_img)

  my_fit <- array(0, dim = dims)

  #slice by slice:
  for (z in seq(dims[3])) {

    tmp_data <- func2std_img[, , z, ]

    dim(tmp_data) <- c(dims[1] * dims[2], dims[4])
    tmp_data <- t(tmp_data)

    # regress out wm
    fit <- lm(tmp_data ~ wm_ts)

    tmp_data <- fit$residuals

    # regress out csf
    fit <- lm(tmp_data ~ csf_ts)

    my_fit[, , z, ] <- t(fit$residuals)

  }

  return(as.nifti(my_fit, value = func2std_img))

}
```

```{r regress_wm_csf_flow}
fmri_flow %>%
  add(what = regress_out_wm_csf,
      inputs = "func2std",
      output = "func2std_out_wm_csf")
```

## Lowpass Filter

```{r filter}
# lowpass filter
filter_func <- function(func, tr) {

  dims <- dim(func)

  n_voxels <- dims[1] * dims[2] * dims[3]

  dim(func) <- c(n_voxels, dims[4])

  func_mat <- matrix(0,
                     nrow = dims[4],
                     ncol = n_voxels)

  chunks <- seq(1, n_voxels, by = 10000)

  for (i in seq_along(chunks)) {

    init <- chunks[i]
    end <- ifelse(i < length(chunks),
                  chunks[i + 1] - 1,
                  n_voxels)

    func_mat[, init:end] <- frequencyFilterfMRI(func[init:end, ] %>% t(),
                                               tr)

  }

  func@.Data <- func_mat %>% t()
  dim(func@.Data) <- dims

  return(func)

}
```

```{r filter_flow}
fmri_flow %>%
  add(what = filter_func,
      inputs = c("func2std_out_wm_csf", "TR"),
      output = "func_filtered")
```

## Extract Time-Series and Compute Correlation

```{r correlation}
# do the parcellation
extract_time_series <- function(bold, corr_label) {

  cmd_base <- get.fsl()

  if (is.nifti(bold)) {

    img <- tempfile(fileext = ".nii.gz")
    writenii(bold, filename = img, dtype = FALSE)

  }

  corrtxt <- tempfile(fileext = ".txt")

  cmd <- paste0(cmd_base,
                "fslmeants -i ", img,
                " --label=", corr_label, " -o ", corrtxt)

  system(cmd, intern = TRUE)

  ts <- read.table(corrtxt, header = FALSE) %>% as.matrix()

  return(ts)

}

# do the correlation
compute_correlation <- function(time_series) {

  r <- cor(time_series)

  zr <- 0.5 * log((1 + r) / (1 - r))

  zr[!is.finite(zr)] <- 0

  return(zr)

}
```

```{r correlation_flow}
fmri_flow %>%
  add(what = extract_time_series,
      inputs = c("func_filtered", "atlas"),
      output = "ts") %>%
  add(what = compute_correlation,
      inputs = "ts",
      output = "cormat")
```


# Final Flow

```{r flow_plot, echo = TRUE, fig.show = 'asis', fig.width = 7, fig.asp = 1}
fmri_flow$plot()
```

# Example


```{r example}
T1_file <- "./resources/rsfMRI/anat.nii.gz"
BOLD_file <- "./resources/rsfMRI/func.nii.gz"
atlas_file <- file.path("./resources/rsfMRI/",
                        'data', 'aal_MNI_V4.nii')

TR <- 2

res <- fmri_flow$execute(inputs = list(T1 = T1_file,
                                       BOLD = BOLD_file,
                                       TR = TR,
                                       atlas = atlas_file),
                         desired_outputs = c("mean_func",
                                             "ts",
                                             "cormat",
                                             "t12std"))
```

## Results

```{r plot_matrix}
plot_matrix <- function(M) {
  
  library(scales)
  library(RColorBrewer)
  
  color_function <- colour_ramp(brewer.pal(11, "RdBu")) 
  heatmap(t(M), Rowv = NA, Colv = NA, 
          col = color_function(seq(0, 1, 0.01)), 
          scale = "none")

}
```


```{r fmri_res, fig.width = 7, fig.asp = 1} 
ortho2(res$mean_func)

ortho2(res$t12std)

plot_matrix(res$cormat)
```


## Full Flow Log

```{r print_log}
fmri_flow$print_log()
```

# Availability